---
- hosts: all

  tasks:
    # - name: Ensure pip modules are installed (Python 2)
    #   pip:
    #     name:
    #       - docker-py
    #       - docker-compose

    - name: Ensure pip modules are installed (Python 3)
      pip:
        name:
          - docker
          - docker-compose

    - name: Login to GitHub registry
      docker_login:
        registry: docker.pkg.github.com
        username: "{{ item.key }}"
        password: "{{ item.value }}"
      with_dict: "{{ github_key }}"

    - name: Download and force recreate skyOS containers
      docker_compose:
        project_src: "{{ skyOS_dir }}"
        pull: True
        state: present
